version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: ~/website
    branches:
      only:
        - master
    steps:
      - checkout
      - run: scp ./public/* $DEPLOYMENT_USER@$DEPLOYMENT_HOST:$DEPLOYMENT_DIR
